name: Build documentation
description: Build documentation with DocFX

inputs:
    docfx-conf-path:
        description: "Path of docfx.json"
        required: true
        default: documentation/docfx.json

runs:
    using: composite
    steps:
        -   name: Build project
            uses: ./.github/workflows/build-project
        -   name: Create documentation landing page
            run: cp README.md documentation/index.md
            shell: bash
        -   name: Build metadata
            run: dotnet docfx metadata --warningsAsErrors ${{ inputs.docfx-conf-path }}
            shell: bash
        -   name: Build website
            run: dotnet docfx build --warningsAsErrors ${{ inputs.docfx-conf-path }}
            shell: bash