name: Scan project
description: Scan project & run tests with Sonar

inputs: 
    sonar-scanner-path:
        description: "Path to the installation folder of the scanner"
        required: true
        default: .sonar/scanner
    project-key:
        description: "Key of the Sonar project"
        required: true
    organization:
        description: "Sonar organization of the project"
        required: true
    token:
        description: "Token used by the scanner"
        required: true

runs: 
    using: "composite"
    steps:
        -   name: Cache SonarCloud packages
            uses: actions/cache@v1
            with:
                path: ~/sonar/cache
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar
        -   name: Cache SonarCloud scanner
            id: cache-sonar-scanner
            uses: actions/cache@v1
            with:
                path: ${{ inputs.sonar-scanner-path }}
                key: ${{ runner.os }}-sonar-scanner
                restore-keys: ${{ runner.os }}-sonar-scanner
        -   name: Install SonarCloud scanner
            if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
            run: |
                mkdir -p ${{ inputs.sonar-scanner-path }}
                dotnet tool update dotnet-sonarscanner --tool-path ${{ inputs.sonar-scanner-path }}
        -   name: Begin Sonar analysis
            run: >-
                ${{ inputs.sonar-scanner-path }}/dotnet-sonarscanner begin 
                /k:"${{ inputs.project-key }}" 
                /o:"${{ inputs.organization }}" 
                /d:sonar.login="${{ inputs.token }}" 
                /d:sonar.host.url="https://sonarcloud.io" 
                /d:sonar.cs.opencover.reportsPaths=variant-tests/coverage.opencover.xml
        -   name: Run tests
            uses: ./.github/workflows/test-project
        -   name: End Sonar analysis
            run: >-
                ${{ inputs.sonar-scanner-path }}/dotnet-sonarscanner end 
                /d:sonar.login="${{ inputs.token }}"