name: Continuous Integration

on:
    push:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    pull_request:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
    format:
        name: Verify coding rules compliance
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
                with:
                    # Allow the validation of all commits
                    fetch-depth: 0
            -   name: Build project
                uses: ./.github/workflows/build-project
            -   name: Verify code
                run: dotnet format . --verify-no-changes -v d
            -   name: Verify commits
                uses: wagoid/commitlint-github-action@v5
                with:
                    helpURL: https://github.com/Thurstag/variant/blob/develop/CONTRIBUTING.md#commits
    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Cache SonarCloud packages
                uses: actions/cache@v1
                with:
                    path: ~/sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Cache SonarCloud scanner
                id: cache-sonar-scanner
                uses: actions/cache@v1
                with:
                    path: .sonar/scanner
                    key: ${{ runner.os }}-sonar-scanner
                    restore-keys: ${{ runner.os }}-sonar-scanner
            -   name: Install SonarCloud scanner
                if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
                run: |
                    mkdir -p .sonar/scanner
                    dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner
            -   name: Begin Sonar analysis
                run: .sonar/scanner/dotnet-sonarscanner begin /k:"Thurstag_variant" /o:"thurst" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=variant-tests/coverage.opencover.xml
            -   name: Build project
                uses: ./.github/workflows/build-project
            -   name: Run tests
                run: dotnet test . -l "console;verbosity=detailed" /p:CollectCoverage=true /p:ExcludeByFile=\"variant-benchmarks/**/*.cs\" /p:CoverletOutputFormat=opencover
            -   name: End Sonar analysis
                run: .sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    build-docs:
        name: Build documentation
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Build documentation
                uses: ./.github/workflows/build-docs