name: Continuous Integration

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"
    workflow_dispatch:

jobs:
    format:
        name: Verify coding rules compliance
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
                with:
                    # Allow the validation of all commits
                    fetch-depth: 0
            -   name: Build project
                uses: ./.github/workflows/build-project
            -   name: Verify code
                run: dotnet format . --verify-no-changes -v d
            -   name: Verify commits
                uses: wagoid/commitlint-github-action@v5
                with:
                    helpURL: https://github.com/thurst-repositories/variant/blob/develop/CONTRIBUTING.md#commits
    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Scan project
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                if: env.SONAR_TOKEN != ''
                uses: ./.github/workflows/scan-project
                with:
                    project-key: ${{ secrets.SONAR_PROJECT_KEY }}
                    organization: ${{ secrets.SONAR_ORGANIZATION }}
                    token: ${{ secrets.SONAR_TOKEN }}
            -   name: Run tests
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                if: env.SONAR_TOKEN == ''
                uses: ./.github/workflows/test-project
    build-docs:
        name: Build documentation
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Build documentation
                uses: ./.github/workflows/build-docs